services:

  kicad:
    image: lscr.io/linuxserver/kicad:latest
    container_name: kicad
    security_opt:
      - no-new-privileges:false
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - CUSTOM_USER=admin
      - PASSWORD=p4ssw0rd      
      - TZ=Europe/Madrid
      - LC_ALL=es_MX.UTF-8
    volumes:
      - ./config:/config
    ports:
      - "8200:3000"
      - "8300:3001"
    restart: unless-stopped
