services:

  kicad:
    image: lscr.io/linuxserver/kicad:latest
    container_name: kicad
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=font-noto-cjk
      - LC_ALL=es_ES.UTF-8     
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
