services:

  kicad:
    image: lscr.io/linuxserver/kicad:latest
    container_name: kicad
    environment:
      - PUID=1000
      - PGID=1000
      - CUSTOM_USER=admin
      - PASSWORD=p4ssw0rd
      - TZ=Europe/Madrid
      - LC_ALL=es_ES.UTF-8
    volumes:
      - ./config:/config
      - ./LC_MESSAGES/kicad.mo:/usr/share/locale/es_ES/LC_MESSAGES/kicad.mo
      - ./projects:/projects
    ports:
      - "8200:3000"
      - "8300:3001"
    shm_size: "1gb"
    restart: unless-stopped
